spring:
  application:
    name: retail-analytics-app
  config:
    import: "optional:configserver:http://localhost:8888/"
  redis:
    cluster:
      #      Comma-delimited list of host:port pairs.
      nodes: localhost:6379,localhost:6372
    username : retail
  jpa:
#    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
#      ddl-auto: update
#      ddl-auto: create
  cloud:
#    function.definition: calculateFavoritesConsumer;orderConsumer
    function:
      definition: calculateFavoritesConsumer;orderConsumer;saveProductConsumer;saveProductConsumerJsonAdapter
    stream:
      default:
        contentType: "application/json"
      bindings:
        calculateFavoritesConsumer-in-0:
          destination: retail.calculateFavorites
          group: ${spring.application.name}
          consumer:
            concurrency: 1
        orderConsumer-in-0:
          destination: retail.customer.orders
          group: ${spring.application.name}
          consumer:
            concurrency: 1
        saveProductConsumer-in-0:
          destination: retail.products
          group: ${spring.application.name}
          consumer:
            concurrency: 1
        saveProductConsumerJsonAdapter-in-0:
          destination: retail.products.json
          group: ${spring.application.name}
          consumer:
            concurrency: 1

      rabbit:
        default:
          group: myQueue
          requiredGroups: true
          dlqQuorum:
            enabled:  true
          quorum:
            enabled: true
        bindings:
          orderConsumer-in-0:
            consumer:
              autoBindDlq: true
              quorum.enabled: true
              dlqQuorum:
                enabled: true
              prefetch: 10000
          calculateFavoritesConsumer-in-0:
            consumer:
              autoBindDlq: true
              quorum.enabled: true
              dlqQuorum:
                enabled: true
              prefetch: 10000
          saveProductConsumer-in-0:
            consumer:
              autoBindDlq: true
              quorum.enabled: false
              containerType: stream
              dlqQuorum:
                enabled: true
              prefetch: 10000
          saveProductConsumerJsonAdapter-in-0:
            consumer:
              autoBindDlq: true
              quorum.enabled: false
              containerType: stream
              dlqQuorum:
                enabled: true
              prefetch: 10000
retail:
  favorites:
    top:
      count: 3
management:
  endpoints:
    web:
      exposure:
        include: info, health
  wavefront:
    application:
      name: retail-analytics-app
      service-name: retail-analytics-app
