spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username : retail
#  redis:
#    url: "redis://localhost:6379"
  redis:
    cluster:
      #      Comma-delimited list of host:port pairs.
      #      ,localhost:6372
      nodes: localhost:6379
