spring:
  data:
    gemfire:
      locators: localhost[10334]
      cache:
        name: server3
        server:
          port: 10334
gemfire:
  gemfire-for-redis-port: 6379
#  remote-distributed-system-id: 1