apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-modern-spring-data
spec:
  title: Starter Workshop
  description: Starter workshop for Educates
  workshop:
    files:
    - image:
        url: $(image_repository)/lab-modern-spring-data-files:latest
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
      - /data-services/gemfire-redis.yml
    packages:
    - name: tce
      files:
      - image:
          url: ghcr.io/vmware-tanzu-labs/educates-extension-packages/tce-0.12:sha-5f9081f
  session:
    namespaces:
      budget: custom
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
      vcluster:
        enabled: true
    objects:
    - apiVersion: data.packaging.carvel.dev/v1alpha1
      kind: Package
      metadata:
        name: kapp-controller.community.tanzu.vmware.com.0.38.3
        namespace: $(session_namespace)-vc
      spec:
        refName: kapp-controller.community.tanzu.vmware.com
        version: 0.38.3
        releaseNotes: kapp-controller 0.38.3 https://github.com/vmware-tanzu/carvel-kapp-controller
        licenses:
        - Apache 2.0
        template:
          spec:
            fetch:
            - imgpkgBundle:
                image: projects.registry.vmware.com/tce/kapp-controller@sha256:3206554c308837edec6b50ae3082ed15c025f0d6a1bc7f3b2ac3602249c8fae5
            template:
            - ytt:
                paths:
                - config/
            - kbld:
                paths:
                - '-'
                - .imgpkg/images.yml
            deploy:
            - kapp:
                rawOptions:
                - --app-changes-max-to-keep=5
    - apiVersion: packaging.carvel.dev/v1alpha1
      kind: PackageInstall
      metadata:
        name: kapp-controller
        namespace: $(session_namespace)-vc
      spec:
        packageRef:
          refName: kapp-controller.community.tanzu.vmware.com
          versionSelection:
            constraints: 0.38.3
        cluster:
          namespace: default
          kubeconfigSecretRef:
            name: $(vcluster_secret)
            key: config
        noopDelete: true
        syncPeriod: 24h
