apiVersion: v1
kind: Pod
metadata:
  name: spring-gf-redis-server
  labels:
    app.kubernetes.io/name: spring-gf-redis-server
spec:
  containers:
    - name: spring-gf-redis-server
      image: cloudnativedata/spring-gf-redis-server:0.0.1-SNAPSHOT
      resources:
        requests:
          memory: "2000Mi"
        limits:
          memory: "2000Mi"
      env:
        - name: "JVM_ARGS"
          value: "-Xms1g -Xmx1g"
        - name: server.port
          value: "7080"
      imagePullPolicy:  Always
      #      imagePullPolicy:  IfNotPresent
      ports:
        - name: redis
          containerPort: 6379
        - name: actuator
          containerPort: 7080
      readinessProbe:
        httpGet:
          path: /actuator/health
          port: 7080
        initialDelaySeconds: 40
        periodSeconds: 20
        timeoutSeconds: 40
        failureThreshold: 30
      livenessProbe:
        httpGet:
          path: /actuator/health
          port: 7080
        initialDelaySeconds: 40
        periodSeconds: 20
        timeoutSeconds: 40
        failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: gf-redis-server
spec:
  selector:
    app.kubernetes.io/name: spring-gf-redis-server
  ports:
    - name: "redis"
      protocol: TCP
      port: 6379
      targetPort: 6379
    - name: "actuator"
      protocol: TCP
      port: 7080
      targetPort: 7080